### PR TITLE
fix: Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by bojanaave** [comment]
LGTM 
@defispartan  @grothem  could you please take a look why GH actions fail? ( I mean on i18n Check / i18n-check (pull_request) action) 
Thanks,
Bojan

**Review by bojanaave — DISMISSED** [review]

**Comment by defispartan** [comment]
@rex4539 Could you run `yarn i18n`, then commit and push the files which are generated? 

This is needed to keep translations up-to-date in CrowdIn

**Comment by rex4539** [comment]
> @rex4539 Could you run `yarn i18n`, then commit and push the files which are generated?
> 
> This is needed to keep translations up-to-date in CrowdIn

Should be ok now :)

**Review by bojanaave — DISMISSED** [review]

**Comment by rex4539** [comment]
Rebased to fix conflict

**Comment by rex4539** [comment]
Rebased to fix conflicts

**Comment by defispartan** [comment]
Hey, sorry for the delay. if you rebase one more time we'll be sure to get it merged

One other thing, is there a reason the `lingui` packages are being bumped in `package.json`, if not, could you revert those changes?

**Comment by rex4539** [comment]
> Hey, sorry for the delay. if you rebase one more time we'll be sure to get it merged
> 
> One other thing, is there a reason the `lingui` packages are being bumped in `package.json`, if not, could you revert those changes?

Rebased and reverted. Not sure how that was changed in the first place.

**Comment by rex4539** [comment]
Fixed one more conflict and rebased.

**Comment by rex4539** [comment]
Rebased and fixed conflict.

**Comment by rex4539** [comment]
@defispartan anything holding the merge?

**Comment by rex4539** [comment]
Withdrawn due to no interest.

**Pull request closed without merging**
