### PR TITLE
feat: add Scroll Alpha Testnet

### PR DESCRIPTION
**Pull request by dghelm**
## General Changes

- Updates `@aave/contract-helpers` to `1.15.0`
- Updates `@bgd-labs/aave-address-book` to `1.21.0`
- Adds Scroll Alpha Testnet network

## Developer Notes

**Context:** Aave Governance [recently voted](https://governance.aave.com/t/deploy-aave-v3-on-scroll-testnet/11861) to allow testnet deployment on Scroll's Alpha Testnet. Scroll Alpha contracts have already been added to `@bgd-labs/aave-address-book` in https://github.com/bgd-labs/aave-address-book/pull/112 and its chainId to `@aave/contract-helpers` in https://github.com/aave/aave-utilities/pull/528

_Contributing Q:_ Please let me know if Issues need to be raised first for your workflow or to create space for discussion. I couldn't find an answer in CONTRIBUTING.md

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [x]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [x]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by MareskoY** [comment]
hello @dghelm  pr is looks find didn't found issues on market,

to get green Ci need to get latests changes from `main`

**Comment by dghelm** [comment]
@grothem @MareskoY Thanks! Should be fixed now.

**Review by defispartan — APPROVED** [review]

**Comment by grothem** [comment]
@dghelm thanks for fixing the merge conflicts.

Sorry there's one more more update. Right now, in the market selector dropdown, the Scroll market is showing a badge for goerli. To fix that, in the `MarketSwitcher.tsx` file, there's an array of testnet chains, on line 38. If you add `Alpha` to that list, then Scroll should show up like this in the market selector:

image

**Comment by dghelm** [comment]
> Sorry there's one more more update. Right now, in the market selector dropdown, the Scroll market is showing a badge for goerli. To fix that, in the `MarketSwitcher.tsx` file, there's an array of testnet chains, on line 38. If you add `Alpha` to that list, then Scroll should show up like this in the market selector:

Thanks for the feedback here -- I chose Goerli intentionally, as our "Scroll Alpha" testnet is an L2 deployed on Goerli (similar to how Optimism Goerli is deployed on Goerli). We don't follow the naming conventions of other projects per se, but I feel like the communication to users is that the other L2s are living on a specific testnet, and I also hoped to make that clear for Scroll.

That said, I'm happy to make any changes your team asks for, but just wanted to confirm that "Alpha" as a badge is the best move here for users.

**Comment by grothem** [comment]
Ok makes sense @dghelm, thanks! Wasn't sure if that was intentional or not as it was the default.

We'll work on getting this merged in.

**Review by grothem — APPROVED** [review]

**Review by TDG510 — APPROVED** [review]

**Pull request merged**
