### PR TITLE
fix: migration credit delegation tx approval

### PR DESCRIPTION
**Pull request by defispartan**
## General Changes

- Implement utilities and UI change so credit delegations approved with tx are persisted between sessions

## Testing

- Try to migrate a supply and borrow position from V2 -> V3
- Approve the allowance and credit delegation by transaction, not signature
- After it's confirmed, clear the browser cache to ensure the modal state is cleared
- Re-open the migration modal and the approval should persist

## Developer Notes

- Update utils to handle passing native token amounts from UI and apply borrow increase within the `migrate` function https://github.com/aave/aave-utilities/pull/525
- Pass current borrow balance instead of projected balance so `isDelegationApproved` can be verified from existing approval

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [ ]  The base branch is set to `main`
- [ ]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [ ]  The General Changes section has been filled out
- [ ]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [ ]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by defispartan** [comment]
Link T-9130

**Comment by MareskoY** [comment]
hello @defispartan 

i use this steps:
```
Try to migrate a supply and borrow position from V2 -> V3
Approve the allowance and credit delegation by transaction, not signature
After it's confirmed, clear the browser cache to ensure the modal state is cleared
Re-open the migration modal and the approval should persist
```

and found that approval not persist in more simple case 

1. Try to migrate a supply and borrow position from V2 -> V3
2. Approve the allowance and credit delegation by transaction, not signature
3. close migration modal
4. open migration modal 

result: 
- approval wasn't persist

**Comment by MareskoY** [comment]
> hello @defispartan
> 
> i use this steps:
> 
> ```
> Try to migrate a supply and borrow position from V2 -> V3
> Approve the allowance and credit delegation by transaction, not signature
> After it's confirmed, clear the browser cache to ensure the modal state is cleared
> Re-open the migration modal and the approval should persist
> ```
> 
> and found that approval not persist in more simple case
> 
> 1. Try to migrate a supply and borrow position from V2 -> V3
> 2. Approve the allowance and credit delegation by transaction, not signature
> 3. close migration modal
> 4. open migration modal
> 
> result:
> 
> * approval wasn't persist

it's reletaed only for MM so QC passed

**Comment by defispartan** [comment]
The bug which occurred above is caused by a feature of MetaMask which works like a bug with increasing balance tokens #1567

**Review by grothem — APPROVED** [review]

**Review by JoaquinBattilana — APPROVED** [review]

**Pull request merged**
