### PR TITLE
fix: fix repay with collateral

### PR DESCRIPTION
**Pull request by sakulstra**
Resolves some issues with the current repay with collateral implementation:
- Excludes pools which are returning 500 errors for swaps involving certain assets (LINK, TUSD)
- Improve slippage estimation for input amounts

### CODE REVIEW

**Comment by sakulstra** [comment]
@defispartan there still seems to be an issue - which weirdly i can only reproduce on ethereum where the flashAmount for some reason is smaller then then maxAmountToPay (reproducible via tenderly).

No idea where it's coming from exactly.

**Comment by defispartan** [comment]
I think the same logic is needed for price impact as well. One thing I didn't know until researching further is that price impact and slippage are not the same thing: https://doc.paraswap.network/price-impact-slippage.

When you test a swap with high slippage, you can see that the expected input amount is calculated *before* price impact is taken into account:

rwc

**Comment by sirsoth** [comment]
Im able to replicate errors on a position with LINK as collateral, unable to repay USDT or DAI

**Comment by sirsoth** [comment]
Just Error getting txParams

**Comment by foodaka** [comment]
is this also related to this issue https://github.com/aave/interface/issues/786 ?

**Comment by sirsoth** [comment]
Looks to me to be the same error

**Review by foodaka — APPROVED** [review]

**Comment by foodaka** [comment]
Thanks @defispartan for investigating and running this down

**Pull request merged**
