### PR TITLE
fix: :bug: fix bug 1671

### PR DESCRIPTION
**Pull request by lyzergic**
switched reserves.length check for borrowDisabled

closes [#1671](https://github.com/aave/interface/issues/1671)

## General Changes

- Fixes 1671 bug
- Adds 0 feature

## Developer Notes

None
---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [x]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [x]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- []  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by defispartan** [comment]
@grothem is going to look into this further to see if this check is the best way to handle the issue

**Comment by lyzergic** [comment]
@grothem switch to Polygon testnet, get some `DAI` from the faucet and some `MATIC` to pay for the transaction. Once you have it in your account go to dashboard and supply a small amount of `DAI`, i supplied `0.001`.
You will see that the `Assets to borrow` card shows the table `<head>` of the assets but it is empty.

It is shown because the code was checking `reserves.length`, which to me seems wrong, because even though I do have reserves, they consist of 0.001 DAI. I changed it to an already existing `!borrowDisable` check.

image

**Comment by grothem** [comment]
Thanks @lyzergic I'm seeing the issue now.

I think your idea is on the right track, but there is an issue with the eth v3 market. Because GHO is in that market, the check for `borrowDisabled` won't work in that case. Here's what it looks like:
image

The reserves available to borrow are filtered out if the available borrow amount in USD is 0. I think we should apply that same logic for GHO so it's consistent, and then we can use the `borrowReserves.length` to determine if we show the header or not. I think the easiest way is to just add an additional`filter on line 152 that always filters on `availableBorrowsInUSD !== '0.00'`, and then modify the existing filter to only check total liquidity or `displayGho`. Hopefully that makes sense 😅

**Comment by lyzergic** [comment]
@grothem pushed changes, did I understand you correctly?

**Comment by grothem** [comment]
Yep, thanks @lyzergic. Looks good!

**Review by grothem — APPROVED** [review]

**Review by JoaquinBattilana — APPROVED** [review]

**Pull request merged**
