### PR TITLE
feat: redesign of 'Your info' section on reserve overview page

### LINKED ISSUE #1264: Re-style 'Your info' section on Reserve page
**Problem**
1. Too many elements, hard to focus and distinguish primary actions.
2. Reserves that have option to supply/borrow wrapped and unwrapped assets, do not show unwrapped ones. User can reach them only via dashboard. 
3. Some warnings (emode+isolation mode) are confusing and don't work properly. 
4. When testnet mode -> faucet button is not obvious. 

Screenshot 2022-10-20 at 19 56 42

**Possible solution**

1. Restyle/move around elements in the section. 
2. Add wrapped/unwrapped tokens, so that user can use both on this page.
3. Double check warnings logic (can be a separate task). 
4. Switch buy button to faucet button when testnet mode, when available. 

**Few examples**
Default asset view
Screenshot 2022-10-20 at 20 02 45

Wrapped/Unwrapped tokens
Screenshot 2022-10-20 at 20 03 24

Warning message
Screenshot 2022-10-20 at 20 04 17

Frozen reserve
Screenshot 2022-10-20 at 20 04 50

Testnet faucet
Screenshot 2022-10-20 at 20 05 26

### PR DESCRIPTION
**Pull request by grothem**
## General Changes

- Restyle 'Your info' section on reserve overview page
- For assets that are a wrapped base asset, there will now be a toggle shown to switch between the two assets in this section
- Closes #1264 

## Developer Notes

- All alerts and warnings were pulled out into a new hook, `useReserveActionState`, which will return the disabled states of the supply/borrow buttons, and what alerts should be shown based off market/user parameters. All alerts should be the same as they were before, but now it is all encapsulated into one hook.

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [x]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [x]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [x]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by iamanastasia** [comment]
Looks great. I've noticed couple of styling issues, and issues related to logic. I'll list it below.

**Styling**

1. When there is only 1 warning, bottom padding seems to be too big. Can we remove it? If we need an extra padding to separate 2+ warnings, then it's better to use same padding but on the top of the banner. 
Screenshot 2022-12-20 at 15 14 13

2. Wrapped/Not wrapped switcher looks too big (Height 52px versus 36 px). There is a switcher of a right size in Repay modal, can we reuse it? 
Screenshot 2022-12-20 at 15 20 06
Screenshot 2022-12-20 at 15 22 14

**Logic**

1. Here is an example of an asset page when e-mode and isolation mode are enabled. It has 2 warnings. I couldn't find same warnings in this pr. 
Screenshot 2022-12-20 at 15 23 21

2. Also couldn't find 'Buy with fiat' button and faucet button. Are they included? 
Screenshot 2022-12-20 at 15 26 17

3. NEW We have tooltip on the dashboard that shows USD value, can we also add it here? 
Screenshot 2022-12-20 at 15 27 03

**Comment by grothem** [comment]
>When there is only 1 warning, bottom padding seems to be too big. Can we remove it? If we need an extra padding to separate 2+ warnings, then it's better to use same padding but on the top of the banner.

Fixed

>Wrapped/Not wrapped switcher looks too big (Height 52px versus 36 px). There is a switcher of a right size in Repay modal, can we reuse it?

Fixed

>Here is an example of an asset page when e-mode and isolation mode are enabled. It has 2 warnings. I couldn't find same warnings in this pr.

I updated the warnings and errors. I do have a question on 'Your wallet is empty' warning. Should that show on the bottom now with all of the other alerts? In that case, there could be 3 alerts that we show there in that case. For now, I didn't include that alert. I also don't have the HF error in there yet.

>Also couldn't find 'Buy with fiat' button and faucet button. Are they included?

That should be in there, although I'm not sure if it will show up in the preview link builds. I tested it out locally and it is showing up.

**Comment by iamanastasia** [comment]
Hey @grothem looks amazing, especially with USD values :) 

1. 'Your wallet is empty' warning — yes, it would be shown on the bottom. I believe it's okay that we have 3+ warnings there, as this task is about restyling. We could work on each warning case-by-case in future tasks. 
2. Fauce/buy button  — okay. 

One more alert I couldn't find:
Here I have isolation mode + emode together. 
Screenshot 2022-12-21 at 15 10 37

If I go to WETH reserve — it shows that I can't supply WETH as collateral. 
Screenshot 2022-12-21 at 15 11 45


But if I go to DAI reserve — there is no message about it :( 
Screenshot 2022-12-21 at 15 12 53

**Comment by grothem** [comment]
@iamanastasia I think the error message not showing on Dai is correct because you can still borrow that asset in isolation and with the emode that you have selected. I checked that case with the existing component and it looks the same.

I also added in the empty wallet alert.

**Comment by iamanastasia** [comment]
> @iamanastasia I think the error message not showing on Dai is correct because you can still borrow that asset in isolation and with the emode that you have selected. I checked that case with the existing component and it looks the same.
> 
> I also added in the empty wallet alert.

Yeah, I can borrow, but if I supply It will not be used as collateral which increases my chances for liquidation. Didn't know that we skip it in the current UI :(  Can we fix it?

**Comment by MareskoY** [comment]
from QA side all looks good =), 
but @iamanastasia mentioned https://github.com/aave/interface/pull/1369#issuecomment-1361516497 it is good to fix if possible

**Comment by grothem** [comment]
thanks @MareskoY, I talked with @iamanastasia about adding this warning. I'm going to create a new issue for improving the warnings/errors shown here. If it was a simple change, I was going to just add it in, but it got a little complicated because now some warnings need to take precedence over others. So for now, the errors/warnings should be exactly the same as before this refactor and we can improve on them after this.

**Review by defispartan — APPROVED** [review]

**Review by foodaka — APPROVED** [review]

**Pull request merged**
