### PR TITLE
chore: replace rotationDelay with check on max retries

### PR DESCRIPTION
**Pull request by defispartan**
## General Changes

RotationProvider currently operates with no limitation on error callbacks, so if a transaction has failing gas estimation the provider will continue to retry and throw errors indefinitely. This adds a limit to the maximum number of loops through the array of rpc providers before throwing an error.

## Developer Notes

Add any notes here that may be helpful for reviewers.

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [ ]  The base branch is set to `main`
- [ ]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [ ]  The General Changes section has been filled out
- [ ]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [ ]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Review by drewcook — COMMENTED** [review]
Should def help cut down requests, maybe needs a unit test on it though

**Comment by grothem** [comment]
Should we keep the rotation delay, but also add in the max retry count?

**Comment by defispartan** [comment]
> Should we keep the rotation delay, but also add in the max retry count?

Rotation delay never made much sense since all rpcs can handle consecutive requests, especially now that there's a limit to the total requests.

It's also a UX downside to have the delay, because in the case of the Paraswap tx handler, the gas estimation error is not shown until the maximum retries completes, so adding the rotation delay would delay the time between the user pressing the transaction button and seeing the error.

**Review by grothem — APPROVED** [review]

**Review by MareskoY — APPROVED** [review]

**Review by drewcook — APPROVED** [review]
LGTM 👍

**Pull request merged**
