### PR TITLE
fix: switch default env from staging to prod

### PR DESCRIPTION
**Pull request by defispartan**
When running the app locally and following the steps from README, the app loads in `staging` env, which is confusing since it disables governance, staking, and production markets

### CODE REVIEW

**Comment by drewcook** [comment]
Good update.

Maybe we also update `CONTRIBUTING.md` line 10 to copy to `env.local` instead of `.env`, unless that's an important difference?  Also, line 32 of the same file, should we keep as is?

**Comment by drewcook** [comment]
Yeah, we may want to change it on line 32 as well since `prod` will be copied over.  Maybe we add a comment in the `.env.example` that says `# Update this to 'staging' to enable testnet mode only, which will eliminate governance, staking, and production markets`

**Comment by defispartan** [comment]
> 

`.env.local` works for both development and production, and has higher precedence than `.env` https://www.querythreads.com/what-is-the-difference-between-env-local-and-env-development-local/ 

Definitely makes sense to update CONTRIBUTING, I'll do that now

**Review by drewcook — APPROVED** [review]
LGTM 👍

**Review by grothem — APPROVED** [review]

**Pull request merged**
