### PR TITLE
chore: hal integration maintenance

### PR DESCRIPTION
**Pull request by tamas-soos**
This is a maintenance PR for the HAL Notification Integration. 

> Inital PR for depricated Aave UI:
https://github.com/aave/aave-ui/pull/324

> The DAO voted on this proposal here:
https://snapshot.org/#/aave.eth/proposal/0xa730caeec3c28e014ff456b454186ef41c6c1f382cf0a7caa3d99c4ae16c8318

> Full discussion on the forum community:
https://governance.aave.com/t/add-hal-push-in-notification-system-on-aave/6512

Changes:
- Added more supported markets
- Fixed visual appearance to be more visible while retaining the UI look and feel

Before change: (barely visible integration)
Screenshot 2022-05-23 at 11 03 18

After change:
Screenshot 2022-05-24 at 15 00 11

### CODE REVIEW

**Comment by sakulstra** [comment]
hey, noticed that we didn't fully finish a refactoring we started.

`halMarketName` is now a config value on ui-config so the code could be simplified a lot like i showcased in this commit https://github.com/aave/interface/compare/main...hal/showcase
Would be cool if you could adjust the pr to account for that. Regarding the design i'll assign @iamanastasia

**Comment by tamas-soos** [comment]
>

**Comment by tamas-soos** [comment]
> hey thx for the pr, while reviewing I noticed that we didn't fully finish a refactoring we started.
> 
> `halMarketName` is now a config value on ui-config so the code could be simplified a lot like i showcased in this commit [main...hal/showcase](https://github.com/aave/interface/compare/main...hal/showcase) Would be cool if you could adjust the pr to account for that. Regarding the design i'll assign @iamanastasia

Hey @sakulstra, thanks for the comment! I will take a look and apply the changes, ty!

(Also ignore the closing of this PR, misclicked and accidentally closed it 😅 )

**Comment by iamanastasia** [comment]
Hi @tamas-soos thanks for the pr!

Have few questions regarding design:
1. How the button works? Is it just an external link? Or does it have some 'notification is enabled/disabled' states? 
2. How would the button look like on mobile screens? I feel there would be little space, especially if market/user has rewards balance. 
3. Can we also provide some link to an FAQ article so that user can explore before clicking?

**Comment by tamas-soos** [comment]
> Hi @tamas-soos thanks for the pr!
> 
> Have few questions regarding design:
> 
> 1. How the button works? Is it just an external link? Or does it have some 'notification is enabled/disabled' states?
> 2. How would the button look like on mobile screens? I feel there would be little space, especially if market/user has rewards balance.
> 3. Can we also provide some link to an FAQ article so that user can explore before clicking?

Hey @iamanastasia, good questions!

1. It's a link that opens in a new tab. I does not have any state, but it does have a tooltip explaining what this button is for.
2. It's mobile responsive, please check video.
3. Where can I find that FAQ article? Isn't the tooltip sufficient for the explanation?

https://user-images.githubusercontent.com/1022631/170680989-b5aea3f0-5415-4ca7-9628-c31a1282ff2b.mp4

**Comment by iamanastasia** [comment]
@tamas-soos 

1. That works
2. Amazing! One small request to double-check alignment with rewards. Right now there are no rewards on supply/borrow, but some users might have old balance there. So there will be another element for that. Just to make sure it would look together like here:
Mobile button version

3. We don't have any FAQ article about HAL integration. However, can we show Snapshot link in the tooltip? Snapshot explains the main idea and it would be a cool way to signal to the community that these type of integrations/proposals are welcomed. 

Tooltip text:

> Set up email notifications to track your Health Factor using the HAL platform.
> This integration was proposed and approved by the community.

**Comment by tamas-soos** [comment]
Thanks @iamanastasia, great comments and suggestions!

Made the requested changes, please check the video.

Let me know if this is good to go or there's something else that I can change.

https://user-images.githubusercontent.com/1022631/171156334-494dbc8e-949e-48f7-a078-a015fa387aee.mp4

**Comment by iamanastasia** [comment]
@tamas-soos this looks great! thank you!

**Comment by defispartan** [comment]
Thanks @tamas-soos 🙌 

I'll review this tomorrow, just need to double-check that the change in src/components/TopInfoPanel/TopInfoPanel.tsx won't affect any other components

**Review by defispartan — APPROVED** [review]
Looks good! Will merge tomorrow

**Comment by defispartan** [comment]
@tamas-soos Could you merge from main and run `yarn i18n` to sync the translations?

**Comment by tamas-soos** [comment]
> @tamas-soos Could you merge from main and run `yarn i18n` to sync the translations?

@defispartan Done 🤙

**Review by defispartan — APPROVED** [review]

**Pull request merged**
