### PR TITLE
remove kovan market and kovan amm market

### PR DESCRIPTION
**Pull request by foodaka**
closes  https://github.com/aave/interface/issues/846

### CODE REVIEW

**Review by sakulstra — APPROVED** [review]

**Review by sakulstra — CHANGES_REQUESTED** [review]
When removing the network config but keeping it in staking it will break.

I think either deploying a new testnet staking, or completely removing it would be reasonable.
In governance we only have mainnet as well and noone ever had a problem with that as it's more reasonable to test on a fork anyways.

**Comment by foodaka** [comment]
@sakulstra @defispartan this is the state now


https://user-images.githubusercontent.com/8342048/172652996-785bc7d7-60c9-4d51-961b-9fc4dce619f6.mov

**Comment by defispartan** [comment]
> @sakulstra @defispartan this is the state now
> Screen.Recording.2022-06-08.at.16.08.33.mov

Not a huge fan of this, when I see this warning my next question would be "How do I access this on an Ethereum fork?", and there's no way to do this from the interface, so this will just create more support questions than it answers. In my opinion this pr should just be removing the Kovan markets, and ensuring that staking is still functional in normal and testnet mode.

Then we can decide in #857 how to display staking/governance in testnet mode, if at all.

**Comment by foodaka** [comment]
yeah i think we can separate the PRs per issue and not let this creep in. The staking was referenced from this issue https://github.com/aave/interface/issues/697

**Comment by foodaka** [comment]
This PR now only in scope for removing kovan as per comment above

**Comment by JoaquinBattilana** [comment]
Kovan was removed on https://github.com/aave/interface/pull/1004, closing this now

**Pull request closed without merging**
