### PR TITLE
chore: ethers upgrade

### PR DESCRIPTION
**Pull request by grothem**
- Upgrade ethers to 5.7.1
- Upgrade @ethersproject/experimental to 5.7.0
- Upgrade @ethersproject/providers to 5.7.1

Changelog:  https://github.com/ethers-io/ethers.js/blob/master/CHANGELOG.md

### CODE REVIEW

**Review by MareskoY — APPROVED** [review]

**Comment by sakulstra** [comment]
> +48.93kb

sounds really bad.

**Comment by grothem** [comment]
> > +48.93kb
> 
> sounds really bad.

Yeah, might be able to cut down on this by being more efficient with our imports. Let me take a look.

**Comment by sakulstra** [comment]
@grothem I think the issue is not shaking or similar, but that the outdated version of @web3-react you're relying on is fixed to 5.5 and gnosis relies on 5.4 so you end up with 3 versions (up from 2, which already wasn't great)

**Comment by MareskoY** [comment]
@grothem pls update with latest `main`

**Pull request closed without merging**
