### PR TITLE
fix: fix fork setup

### PR DESCRIPTION
**Pull request by sakulstra**
When you are on a fork, the ui will NOT tell you to switch network when mm selects mainnet, which imo is a quite serious issue.

I think introduced here https://github.com/aave/interface/pull/887/files or even present before.

### CODE REVIEW

**Comment by grothem** [comment]
Good catch, yeah it was introduced in that PR because you couldn't stake on a fork before those changes. I think the same issue will be in the `StakeCooldownModalContent` and `StakeRewardClaimModalContent`, introduced here: https://github.com/aave/interface/pull/900

**Comment by sakulstra** [comment]
@grothem pushed a fix for the others as well

**Review by grothem — APPROVED** [review]

**Comment by sakulstra** [comment]
@grothem rebased and added https://github.com/aave/interface/pull/965/commits/ee6f64b77da804dc4ebfcbcda20cc37e85baf4a8 since you reviewed - this commit makes the ui show "<network> fork" on the switch network dialog and also in the wallet dropdown
image

**Comment by bojanaave** [comment]
checked on fix/fix-fork-setup and looks fine

**Comment by grothem** [comment]
Nice! Looks good

**Review by grothem — APPROVED** [review]

**Pull request merged**
