### PR TITLE
chore: testnet and ui helper contract updates

### PR DESCRIPTION
**Pull request by grothem**
- V3 testnet markets removed: Arbitrum Rinkeby, Harmony Testnet, Optimism Kovan
- V2 testnet markets removed: Eth Kovan and AMM Kovan
- V2 testnet added: Goerli
- Updated UI helper contracts to use new verified contracts
- When testnet mode is enabled, default the market switcher dropdown to V3

### CODE REVIEW

**Comment by defispartan** [comment]
V3 UiPoolDataProvider contracts are failing with overflow error. The addition of Goerli V2 was copied to #1052

**Review by bojanaave — APPROVED** [review]

**Comment by defispartan** [comment]
Docs PRs:
https://github.com/aave/docs-v3/pull/19
https://github.com/aave/docs-v2/pull/8

Still needs updated V2 Goerli deployment

**Comment by kartojal** [comment]
> Docs PRs: [aave/docs-v3#19](https://github.com/aave/docs-v3/pull/19) [aave/docs-v2#8](https://github.com/aave/docs-v2/pull/8)
> 
> Still needs updated V2 Goerli deployment

Goerli V2 have been updated since last weekend, let me know if is something else

**Comment by MareskoY** [comment]
there are few problems 

**BUG1**
Mumbai faucet for don't work for each asset
```
cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":108,\"error\":{\"code\":3,\"message\":\"execution reverted: ERC20: transfer amount exceeds balance\",\"data\":\"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000\"}}","error":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0x0\",\"from\":\"0xe4217040c894e8873ee19d675b6d0eec992c2c0d\",\"to\":\"0x0b3c23243106a69449e79c14c58bb49e358f9b10\",\"data\":\"0x40c10f19000000000000000000000000001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f00000000000000000000000000000000000000000000021e19e0c9bab2400000\"}],\"id\":108,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-mumbai.g.alchemy.com/v2/demo"}, method="estimateGas", transaction={"from":"0xE4217040c894e8873EE19d675b6d0EeC992c2c0D","to":"0x0b3C23243106A69449e79C14c58BB49E358f9B10","value":{"type":"BigNumber","hex":"0x00"},"data":"0x40c10f19000000000000000000000000001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f00000000000000000000000000000000000000000000021e19e0c9bab2400000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
```
Screenshot 2022-08-31 at 11 33 39


**BUG2**
for avalanche fuji asset available only 2 asset
Screenshot 2022-08-31 at 11 40 17

and v2 fuji market have only 4 assets, and real market has more assets in the list

Screenshot 2022-08-31 at 11 41 13

**Comment by defispartan** [comment]
> there are few problems
> 
> **BUG1** Mumbai faucet for don't work for each asset
> 
> ```
> cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":108,\"error\":{\"code\":3,\"message\":\"execution reverted: ERC20: transfer amount exceeds balance\",\"data\":\"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000\"}}","error":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"value\":\"0x0\",\"from\":\"0xe4217040c894e8873ee19d675b6d0eec992c2c0d\",\"to\":\"0x0b3c23243106a69449e79c14c58bb49e358f9b10\",\"data\":\"0x40c10f19000000000000000000000000001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f00000000000000000000000000000000000000000000021e19e0c9bab2400000\"}],\"id\":108,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-mumbai.g.alchemy.com/v2/demo"}, method="estimateGas", transaction={"from":"0xE4217040c894e8873EE19d675b6d0EeC992c2c0D","to":"0x0b3C23243106A69449e79C14c58BB49E358f9B10","value":{"type":"BigNumber","hex":"0x00"},"data":"0x40c10f19000000000000000000000000001b3b4d0f3714ca98ba10f6042daebf0b1b7b6f00000000000000000000000000000000000000000000021e19e0c9bab2400000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
> ```
> 
> Screenshot 2022-08-31 at 11 33 39
> 
> **BUG2** for avalanche fuji asset available only 2 asset Screenshot 2022-08-31 at 11 40 17
> 
> and v2 fuji market have only 4 assets, and real market has more assets in the list
> 
> Screenshot 2022-08-31 at 11 41 13

For Bug 1, all of the test assets have been minted on this network. A separate deployment of test markets with a new version of the faucet contract is in the works and will be in a separate update.

For Bug 2, the assets available on test networks depend on the oracles on the network. It's to be expected that test assets may not line up 1:1 with production networks or between V2-V3.

**Review by defispartan — APPROVED** [review]
Tested all markets 👍

**Pull request merged**
