### PR TITLE
fix: read-only mode text

### PR DESCRIPTION
**Pull request by iamanastasia**
## General Changes

Watch-only mode -> Read-only mode

- Wallet connect modal window — changed input label, placeholder and tooltip text, also button text
- Profile dropdown — changed warning message
- TX window — changed warning message

## Developer Notes

Add any notes here that may be helpful for reviewers.

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [ ]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [ ]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [x]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Review by grothem — DISMISSED** [review]

**Review by 0x4Graham — DISMISSED** [review]

**Review by drewcook — COMMENTED** [review]
There are a few other periphery renames that need to happen too.  Around a11y fields, an error message, and a comment.

image

But furthermore, we are still storing and working with the `watchModeOnlyAddress` throughout the code.

image

On all these instances, the user doesn't visually see it in the UI, but it is still there in our codebase.  So, I think if we are to rename from `watch mode` to `read mode`, then not only do we need to make updates in the UI to reflect this, but we should also update all the other instances of it. This is pretty typical when doing name changes, but I figure I'd point this out.

I'll handle updating the remaining name changes so don't worry about that.

On all other fronts, your changes look good!

**Review by drewcook — COMMENTED** [review]
I've pushed up all the non-visual changes @defispartan @grothem

**Comment by iamanastasia** [comment]
@drewcook thanks for the assistance!

**Comment by bojanaave** [comment]
LGTM.
Screen Shot 2022-12-29 at 10 10 09
-a7cf4cd
Screen Shot 2022-12-29 at 10 11 35
be547.png)
Screen Shot 2022-12-29 at 10 11 53

**Review by MareskoY — APPROVED** [review]

**Review by defispartan — APPROVED** [review]

**Pull request merged**
