### PR TITLE
feat: warn about governance in borrow modal

### PR DESCRIPTION
**Pull request by reem**
Adds a small warning to the borrow modal which reminds the user that governance can change parameters which can affect the health factor of their position and reminds them to keep an eye on the governance forum to stay ahead of such changes.

Voted on by the community: https://snapshot.org/#/aave.eth/proposal/bafkreiaiba6o7b3bsosligjrxnzlxgvkckgqriqlle6d4xa3i4qcfljmru

### CODE REVIEW

**Comment by reem** [comment]
Example of the warning:

Screen Shot 2022-08-03 at 2 46 26 PM

**Comment by defispartan** [comment]
@reem Thanks for the contribution!

**Comment by defispartan** [comment]
@iamanastasia What are your thoughts on this?
 
Here's a screenshot with the HF risk warning as well: 

BorrowModalWarning

**Comment by grothem** [comment]
@reem thanks for the PR! Sorry for the delay in reviewing this, looks good. Could you resolve the merge conflicts?

**Comment by reem** [comment]
Rebased to resolve conflicts, let me know if I can do anything else

**Comment by defispartan** [comment]
Hey @reem, just two small things:

First, could you run `yarn i18n` and commit/push the files which are generated to update the localization?

Second, could you replace all instances of `Alert` in this file with `Warning` imported with `import { Warning } from 'src/components/primitives/Warning';`? This applies some consistent styling to warning messages.

**Comment by reem** [comment]
Done, thanks for the review, let me know if there's anything else I can follow up on

**Comment by defispartan** [comment]
> Done, thanks for the review, let me know if there's anything else I can follow up on
> 
> Note I did not edit the other usage of Alert as it has `severity="error"` so is not a warning, let me know if I should replace that as well

Thanks for updating, looks good! Hope you don't mind I added a link to the snapshot vote to the PR description

**Review by defispartan — APPROVED** [review]

**Comment by bojanaave** [comment]
LGTM

**Comment by defispartan** [comment]
@foodaka Could you approve and merge tomorrow?

**Review by foodaka — APPROVED** [review]

**Comment by foodaka** [comment]
hi @reem could you please fix the merge conflicts and then we will merge

**Review by foodaka — CHANGES_REQUESTED** [review]
merge conflicts

**Review by bojanaave — DISMISSED** [review]

**Comment by defispartan** [comment]
@reem For some reason it does not appear on GitHub but cloning locally there is a conflict with localization, so if you could rebase with main, then run and push `yarn i18n` again then it will be good to merge :)

**Comment by reem** [comment]
Rebased again, lmk if this looks good

**Review by foodaka — APPROVED** [review]

**Review by drewcook — APPROVED** [review]

**Pull request merged**
