### PR TITLE
fix: don't clear account in connect wallet callback

### PR DESCRIPTION
**Pull request by grothem**
## General Changes

- Fixes a bug where the app was not working inside of the gnosis safe UI

## Developer Notes

It's not clear exactly why this caused an issue, but calling `setAccount` (which changed global app state) inside of the connect wallet callback was causing the connect logic to fire multiple times.

---

## Author Checklist

Please ensure you, the author, have gone through this checklist to ensure there is an efficient workflow for the reviewers.

- [x]  The base branch is set to `main`
- [x]  The title is using [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) formatting
- [ ]  The Github issue has been linked to the PR in the Development section
- [x]  The General Changes section has been filled out
- [x]  Developer Notes have been added (optional)

**If the PR is ready for review:**

- [x]  The PR is in `Open` state and not in `Draft` mode
- [x]  The `Ready for Dev Review` label has been added

## Reviewer Checklist

Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues that may occur.

- [ ]  End-to-end tests are passing without any errors
- [ ]  Code style generally follows existing patterns
- [ ]  Code changes do not significantly increase the application bundle size
- [ ]  If there are new 3rd-party packages, they do not introduce potential security threats
- [ ]  If there are new environment variables being added, they have been added to the `.env.example` file as well as the pertinant `.github/actions/*` files
- [ ]  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
- [ ]  Code changes have been quality checked in the ephemeral URL
- [ ]  QA verification has been completed
- [ ]  There are two or more approvals from the core team
- [ ]  Squash and merge has been checked

### CODE REVIEW

**Comment by defispartan** [comment]
With this change, if you mock a wallet address, then switch to a connected wallet, there will be a network request for the mocked wallet address due to the delay in updating `account`

**Review by defispartan — DISMISSED** [review]
Looks good

**Review by foodaka — APPROVED** [review]

**Comment by bojanaave** [comment]
Hi @grothem  opening the latest IPFS link (from this ticket) through gnosis safe app it loading takes ~20-25sec and a lot of errors appear in the browser console ( and app.aave UI is not fully rendered) is it something that we can fix in scope of this ticket?
NOTE: Everything else works as expected ( Supply / withdraw / borrow) 
Screen Shot 2022-12-21 at 13 25 49

**Comment by grothem** [comment]
@bojanaave some of those errors are expected, like the address screening calls. I wonder if the slowness is due to the preview links since they aren't the most reliable. I just tried again using the link and it loaded pretty quick for me (inside of gnosis).

**Comment by bojanaave** [comment]
Thanks @grothem  in that case we can consider this ticket is verified.

**Review by bojanaave — APPROVED** [review]

**Review by defispartan — APPROVED** [review]

**Pull request merged**
